cmake_minimum_required(VERSION 3.14)
project(EasyExamples)

option(BUILD_WINDOWS_EXAMPLES "Build Win32 GUI examples" ON)
option(BUILD_CONSOLE_EXAMPLES "Build console examples" ON)

if(BUILD_CONSOLE_EXAMPLES)
    add_subdirectory(VsCodeCmakeEasiest)
    add_subdirectory(VsCodeCmakeW2src)
    add_subdirectory(ModernCPP_Containers)
    add_subdirectory(ExceptionHandling)
    add_subdirectory(PolimorficSmart)
endif()

if(BUILD_WINDOWS_EXAMPLES)
    if(WIN32)
        add_subdirectory(WindowsHEasiest)
        add_subdirectory(WindowsAndCommctrlH)
        add_subdirectory(WindowsDialog)
        add_subdirectory(Gdiplus_H)
        add_subdirectory(ResourcesAndGdiplus_H)
        add_subdirectory(ResourcesProgressBar)
        add_subdirectory(WindowsDrawing)
    else()
        message(STATUS "Skipping Win32 examples because host platform is not Windows")
    endif()
endif()
